default: &default
  adapter: postgresql
  encoding: unicode
  pool: 10
  prepared_statements: true
  advisory_locks: false
    
development:
  <<: *default
  database: money_unicorn_development

test:
  <<: *default
  database: money_unicorn_test

production:
  primary: &primary_production
    <<: *default
    database: money_unicorn_production
    username: money_unicorn
    password: <%= ENV["MONEY_UNICORN_DATABASE_PASSWORD"] %>
  cache:
    <<: *primary_production
    database: money_unicorn_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: money_unicorn_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: money_unicorn_production_cable
    migrations_paths: db/cable_migrate
